# Generated by Django 2.2.4 on 2019-09-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AddField(model_name="walletuser", name="wallet_id", field=models.CharField(max_length=50, null=True))
    ]
